#!/bin/bash

if [[ $# -gt 1 ]]; then
        echo -e "\e[31mToo many parameters!\e[0m"
        exit 1
fi

if [ $# -eq 0 ]; then
    count=1
elif [ $# -eq 1 ] && [[ "$1" =~ ^[0-9]+$ ]]; then
    if [ "$1" -ge 1 ]; then
        count=$1
    fi
fi

meow_sigint() {
	echo -e "\e[38;5;$(( $RANDOM % 255 ))m\e[1A\r\e[K"
	echo -e "You stopped the avalanche of kitties!\nHow dare you?!\nYou bastard..."
	echo -e "\e[0m"
	exit 1
}

# Definiowanie 10 kotków ASCII art
cat1="
 /\\_/\\
( o.o )
 > ^ <
"

cat2="
 /\\_/\\
( ^_^ )
  >^<
"

cat3="
 /\\_/\\
(=^_^=)
 (\")(\")
"

cat4="
 /\\_/\\
(=^.^=)
 (\")(\")
"

cat5="
 /\\_/\\
( o.o )
  > ^ <
"

cat6="
 /\\_/\\
(=^_^=)
  > ^ <
"

cat7="
 /\\_/\\
( ^_^ )
  > ^ <
"

cat8="
 /\\_/\\
( -.- )
  > ^ <
"

cat9="
 /\\_/\\
( O_O )
  > ^ <
"

cat10="
 /\\_/\\
( o.o )
 (\")(\")
"

# Dodanie kotków do tablicy
cats=(
"$cat1"
"$cat2"
"$cat3"
"$cat4"
"$cat5"
"$cat6"
"$cat7"
"$cat8"
"$cat9"
"$cat10"
)

i=1
while [[ i -le $count ]]; do

	trap meow_sigint SIGINT

        # Losowanie kotka
        cat_number=$(( $RANDOM % ${#cats[@]} ))

        # Wybór kotka
        cat_art="${cats[$cat_number]}"

        # Losowanie koloru kotka
        cat_color="\e[38;2;$(( $RANDOM % 255 ));$(( $RANDOM % 255 ));$(( $RANDOM % 255 ))m"
        
        # Losowanie, czy pojawi się "meow"
        show_meow=$(( $RANDOM % 100 ))

        # Wyświetlanie kotka w losowym kolorze
        echo -e "${cat_color}${cat_art}\e[0m"

        # Jeżeli ma się pojawić "meow"
        if [ $show_meow -le 25 ]; then
            # Losowanie koloru dla "meow", innego niż kolor kotka
            meow_color="\e[38;2;$(( ($RANDOM % 255 + 1) % 255 ));$(( $RANDOM % 255 ));$(( $RANDOM % 255 ))m"
            echo -e "\e[3A\e[8C${meow_color}meow\e[0m\e[2B"
        fi

        sleep 0.2
        i=$(( i + 1 ))
done
